### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by maxpanda** [Tomshiii/ahk#15]
Hello! I am trying to install the latest **v2.10.1.exe**, I am a first time user and get the error below during the initial process:

![image](https://user-images.githubusercontent.com/7445488/220859932-6bde3c39-e4d6-4659-8a38-d1dbda35ba2f.png)
![image](https://user-images.githubusercontent.com/7445488/220860816-6c05b93d-7345-4385-9d66-ad2f98afdf6a.png)

I have tried going back to the next two previous releases **v2.10.0.1** and **v2.10** and get a little further but encounter this error when running any of the scripts, I clicked on My Scripts.ahk first:

![image](https://user-images.githubusercontent.com/7445488/220860476-51ef6c29-fac1-43e5-8098-59d112cd1f97.png)

I hope I have provided enough info! :)

**Comment by Tomshiii** [comment]
Hey hey!
Thanks for bringing this to my attention!
This was a careless mistake created by me in a recent version release so it's very _"lucky"_ you stumbled across it so soon!

Basically during my `.exe` creation process I was copying over an entire library of functions which in turn accidentally ended up copying over a call to a function that isn't defined causing your initial error. I've gone ahead and fixed that [here](https://github.com/Tomshiii/ahk/commit/6ea9e9f9cbdbdf2339cb017a1645bdba8eecebf8).
I've also attached a `.zip` to this post that contains a new install `.exe`, give it a try and see if it gets through the extraction process!

The second error you encountered could be one of two things (potentially, I'm taking a stab in the dark as the error ahk spat out for you isn't very descriptive). Either;

- The `settings.ini` file may not have generated properly which can cause issues, delete it from `My Documents\tomshi\settings.ini` and try again! 
- Something *may* have gone wrong during the symlink creation process. Try the `.exe` I've attached, make sure to select the symlink option in the gui that should appear. (then verify it worked by going to your `My Documents\AutoHotkey\` folder and checking to see if there's a folder `\Lib` if clicking that folder takes you to your `C:\Tomshii AHK\` folder then it worked.

If you still get the error after that, let me know and we can try and track it down!

**Comment by maxpanda** [comment]
Seems that everything works fine with the new .exe ! :)

Thank you so much for the timely reply! I will now start the process of figuring out what to do and learning all of this stuff in-between my ongoing projects :)

I'll be sure to pop back if I break something :)

**Comment by Tomshiii** [comment]
Awesome, I’m glad that worked! I'll push that as a proper patch tomorrow then. Feel free to open more issues if you encounter any consistent issues! (there's always plenty of them ahk be jank sometimes haha)
