### ISSUE TITLE
Failed attempt to launch program or document

### ISSUE THREAD

**Issue by Teighe** [Tomshiii/ahk#6]
Hi there. I'm trying to learn how to use your scripts with AHK but I've run into a roadblock right at the beginning. Could totally be user error! I've got both 7zip and PowerShell installed. I also have AHK installed. When I try to run v2.8.1, I recieve an error saying that it can't find releaseGUI.ahk. However, I found that file in AutoHotkey Scripts\ahk-2.8.1\Support Files\Release Assets\releaseGUI.ahk. So, it's definitely there. 

Any help you can offer would be really appreciated!
--------------

Error: Failed attempt to launch program or document:
Action: <G:\Resources\AutoHotkey Scripts\Support Files\Release Assets\releaseGUI.ahk>
Params: <>

Specifically: The system cannot find the file specified.

▶	019: Run(A_ScriptDir "\Support Files\Release Assets\releaseGUI.ahk")

Call stack:
*#1 (19) : [Run] Run(A_ScriptDir "\Support Files\Release Assets\releaseGUI.ahk")
*#1 (19) : [] Run(A_ScriptDir "\Support Files\Release Assets\releaseGUI.ahk")
> Auto-execute

**Comment by Tomshiii** [comment]
Interesting, it might be trying to run the file before it even exists yet (might be a case of my pc is really fast so anything slower might run into an issue).
I'll take a look at this later today - for now all you have to do is run either that releaseGUI script and read the readme.md file in the same directory or simply run the symlink script also in the same directory. From there you can get started as normal. I'll report back when I can take a look

**Comment by Tomshiii** [comment]
If you could give me and more information in the meantime that would be great (exact steps you took, what the exact directory path was that you tried to run the exe file in, ahk version, etc etc)

**Comment by Tomshiii** [comment]
I created a [branch](/tomshiii/ahk/tree/fixInstaller) and attatched it to this issue to track trying to fix it, try the installer I'm attatching to this comment to see if my hunch was correct, otherwise provide the info above and I'll try to track down the issue.

[v2.8.2-alpha.1.zip](https://github.com/Tomshiii/ahk/files/10203471/v2.8.2-alpha.1.zip)

**Comment by Tomshiii** [comment]
I'm hoping #7 has fixed the issue, if it hasn't feel free to reopen this issue in the future or open a new issue with further details
